module.exports = {
  PORT: process.env.port,
  DB_URL: process.env.DB_URL,
  MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
  EXCHANGE_NAME: "ONLINE_SHOPPING",
  SHOPPING_BINDING_KEY: "SHOPPING_SERVICE",
  CUSTOMER_BINDING_KEY: "CUSTOMER_SERVICE",
  QUEUE_NAME: "PRODUCT_QUEUE",
  PRODUCT_BINDING_KEY: "PRODUCT_SERVICE",
};
